apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  namespace: curso
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: danielribeirojr/app-sample-istio:v1
        imagePullPolicy: Always  # Definir imagePullPolicy para Always
        ports:
        - containerPort: 7001

---

apiVersion: v1
kind: Service
metadata:
  name: api-rest-service
  namespace: curso
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 7001
      nodePort: 32001
  type: NodePort
